<?php

declare(strict_types=1);

namespace App\DTO;

use Symfony\Component\Validator\Constraints as Assert;

/**
 * Immutable Data Transfer Object for transfer requests.
 * All fields are validated before reaching the service layer.
 */
readonly class TransferRequest
{
    public function __construct(
        #[Assert\NotBlank(message: 'Source account ID is required.')]
        #[Assert\Uuid(message: 'Source account ID must be a valid UUID.')]
        public string $sourceAccountId,

        #[Assert\NotBlank(message: 'Destination account ID is required.')]
        #[Assert\Uuid(message: 'Destination account ID must be a valid UUID.')]
        public string $destinationAccountId,

        #[Assert\NotBlank(message: 'Amount is required.')]
        #[Assert\Positive(message: 'Amount must be a positive number.')]
        #[Assert\Regex(
            pattern: '/^\d{1,18}(\.\d{1,8})?$/',
            message: 'Amount must be a valid decimal with up to 8 decimal places and max 18 integer digits.'
        )]
        public string $amount,

        #[Assert\NotBlank(message: 'Currency is required.')]
        #[Assert\Currency(message: 'Currency must be a valid ISO 4217 currency code.')]
        public string $currency,

        /**
         * Idempotency key — UUID v4 generated by the client.
         * Must be unique per logical request. Reusing the same key
         * with different parameters returns the original response.
         */
        #[Assert\NotBlank(message: 'Idempotency key is required.')]
        #[Assert\Uuid(message: 'Idempotency key must be a valid UUID.')]
        public string $idempotencyKey,
    ) {}

    /**
     * Returns true if source and destination are the same account.
     */
    public function isSelfTransfer(): bool
    {
        return $this->sourceAccountId === $this->destinationAccountId;
    }
}
